### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [simsong/dfxml#13]
I would like to point out that identifiers like "[`_DFXML_READER_H_`](https://github.com/simsong/dfxml/blob/2e0bb826909d987fcc97d6a1d9bf1e12be357692/src/dfxml_reader.h#L1)" and "[`_DFXML_WRITER_H_`](https://github.com/simsong/dfxml/blob/a64c13dd95793c84356397e8f4b447c7d300f7bb/src/dfxml_writer.h#L8)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by simsong** [comment]
Thanks for catching these. Please submit a pull request.

**Comment by simsong** [comment]
> do not fit

**Comment by elfring** [comment]
Thanks for [your adjustment of two include guards](https://github.com/simsong/dfxml/commit/2b975ff4edf3c235ee28cb03fcaf71a42b64bdcc "Renaming of two include guards").

**Comment by elfring** [comment]
[I suggest](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") to [reconsider further identifiers](https://github.com/simsong/dfxml/blob/60ebec538f395e56306dc58b0207e361e506b277/src/dfxml_writer.h#L50 "Update candidate").

**Comment by simsong** [comment]
As before, you are welcome to submit a pull request! But I will get to these. Thanks.

**Comment by elfring** [comment]
How do you think about to [rename a class like “`hash__`”](https://github.com/simsong/dfxml/blob/60ebec538f395e56306dc58b0207e361e506b277/src/hash_t.h#L71 "Update candidate: hash__ class")?

**Comment by simsong** [comment]
I agree that a class rename is appropriate. I have done a lot of work on this class just now, though. Let me push it back and we can discuss.

**Comment by elfring** [comment]
Is the renaming of affected identifiers still incomplete?

**Comment by simsong** [comment]
I don’t know. Can you please submit a pull request?

**Comment by elfring** [comment]
>I don’t know.

Would you like to adjust the usage of the identifier “`hash__`”?

**Comment by simsong** [comment]
Adjust it to what?

**Comment by elfring** [comment]
Perhaps “`dfxml::hash`”?

**Comment by simsong** [comment]
I hadn’t thought about using a name space. Good idea. I will give it a try.


----
Sent from my phone.

On Jul 1, 2020, at 7:35 AM, Markus Elfring <notifications@github.com> wrote:

﻿
Perhaps “dfxml::hash”?
