### ISSUE TITLE
Patch: dfxml builds under openssl 1.1

### ISSUE THREAD

**Issue by dkogan** [simsong/dfxml#16]
Hi. Openssl 1.1 changed their API somewhat. A patch to make it work for both 1.0 and 1.1:

```
Index: tcpflow/src/dfxml/src/hash_t.h
===================================================================
--- tcpflow.orig/src/dfxml/src/hash_t.h
+++ tcpflow/src/dfxml/src/hash_t.h
@@ -189,7 +189,7 @@ inline std::string digest_name<sha512_t>

 template<const EVP_MD *md(),size_t SIZE> 
 class hash_generator__ {           /* generates the hash */
-    EVP_MD_CTX mdctx;       /* the context for computing the value */
+    EVP_MD_CTX* mdctx;      /* the context for computing the value */
     bool initialized;         /* has the context been initialized? */
     bool finalized;
     /* Static function to determine if something is zero */
@@ -202,21 +202,21 @@ class hash_generator__ {          /* generates
 public:
     int64_t hashed_bytes;
     /* This function takes advantage of the fact that different hash functions produce residues with different sizes */
-    hash_generator__():mdctx(),initialized(false),finalized(false),hashed_bytes(0){ }
+    hash_generator__():mdctx(NULL),initialized(false),finalized(false),hashed_bytes(0){ }
     ~hash_generator__(){
        release();
     }
     void release(){            /* free allocated memory */
        if(initialized){
-       EVP_MD_CTX_cleanup(&mdctx);
+       EVP_MD_CTX_destroy(mdctx);
            initialized = false;
            hashed_bytes = 0;
        }
     }
     void init(){
        if(initialized==false){
-       EVP_MD_CTX_init(&mdctx);
-       EVP_DigestInit_ex(&mdctx, md(), NULL);
+       mdctx = EVP_MD_CTX_create();
+       EVP_DigestInit_ex(mdctx, md(), NULL);
            initialized = true;
            finalized = false;
            hashed_bytes = 0;
@@ -228,7 +228,7 @@ public:
            std::cerr << "hashgen_t::update called after finalized\n";
            exit(1);
        }
-   EVP_DigestUpdate(&mdctx,buf,bufsize);
+   EVP_DigestUpdate(mdctx,buf,bufsize);
        hashed_bytes += bufsize;
     }
     hash__<md,SIZE> final() {
@@ -242,7 +242,7 @@ public:
        }
        hash__<md,SIZE> val;
        unsigned int len = sizeof(val.digest);
-   EVP_DigestFinal(&mdctx,val.digest,&len);
+   EVP_DigestFinal(mdctx,val.digest,&len);
        finalized = true;
        return val;
     }
```

**Comment by simsong** [comment]
Thanks!

**Comment by simsong** [comment]
WIll you be submitting this as a pull request?

**Comment by dkogan** [comment]
I hope not. I suppose I could

1. use the github web ui to fork this project
2. check out the sources
3. apply patch
4. commit
5. push
6. use the web ui to create pull request
7. delete my github fork
8. delete local copy of this fork

but I'd rather not. The process for you to merge this isn't entirely without tedium, but much better I think. Let me know if you REALLY want a pull request.

**Comment by simsong** [comment]
Well I'm not actively developing this at the present. Perhaps someone else will provide the pull request.

**Comment by ajnelson** [comment]
Hello, Dima.  I made a Git commit of your patch and am tracking its merging into`master` in [this branch](https://github.com/simsong/dfxml/tree/issue_16).  I will be happy to merge this into `master` after testing with OpenSSL 1.1.  However, I don't have a system on hand that can reproduce the issue.  (For instance, Ubuntu 16.10 [provides](https://launchpad.net/ubuntu/yakkety/+source/openssl) 1.0.2g.)  Would you mind providing a little information on how you made the issue, like distro you were using, and/or how you installed OpenSSL 1.1?

**Comment by dkogan** [comment]
Alex Nelson <notifications@github.com> writes:

> Hello, Dima. I made a Git commit of your patch and am tracking its
> merging into`master` in [this
> branch](https://github.com/simsong/dfxml/tree/issue_16). I will be
> happy to merge this into `master` after testing with OpenSSL 1.1.

Thank you very much for doing this


> However, I don't have a system on hand that can reproduce the issue.
> (For instance, Ubuntu 16.10
> [provides](https://launchpad.net/ubuntu/yakkety/+source/openssl)
> 1.0.2g.) Would you mind providing a little information on how you made
> the issue, like distro you were using, and/or how you installed OpenSSL
> 1.1?

This was in response to this:

  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828570

As the bug report says, there are openssl 1.1 packages in
debian/experimental.

The new release of the debian tcpflow package (tcpflow/1.4.5+repack1-3)
contains two patches to fix this bug. One patch is this dfxml issue. The
other is this:

  https://github.com/simsong/tcpflow/issues/135

Let me know if you need more help reproducing the problem.

**Comment by ajnelson** [comment]
If you have a debian/experimental machine with build tools and that 1.1 version of OpenSSL handy, would you mind running these commands?  If the end result is `0` then I'll merge the fix into master.

    git clone --branch=issue_16 https://github.com/simsong/dfxml.git dfxml_issue_16
    cd dfxml_issue_16/src
    ./bootstrap.sh && ./configure && make && make check
    echo $?

If you don't have a machine handy, I'll spin up a VM myself, but may not be able to do so soon.

**Comment by dkogan** [comment]
Alex Nelson <notifications@github.com> writes:

> If you have a debian/experimental machine with build tools and that
> 1.1 version of OpenSSL handy, would you mind running these commands?
> If the end result is `0` then I'll merge the fix into master.
>
>     git clone --branch=issue_16 https://github.com/simsong/dfxml.git dfxml_issue_16
>     cd dfxml_issue_16/src
>     ./bootstrap.sh && ./configure && make && make check
>     echo $?

I just did this, and the result is indeed 0, but the configure said

   checking for SSL_library_init in -lssl... no

because this function was renamed in openssl1.0. That's the other patch
(in the tcpflow tracker; link is in the last email). If this isn't
found, is the test suite result still valid? There are no overt
indications that anything went wrong.

**Comment by ajnelson** [comment]
`make check` in DFXML doesn't seem to do much.  I was satisfied that your change doesn't break the build, but let's check tcpflow too.  Could you try these commands in that same environment?

    git clone --branch=issue_135 https://github.com/ajnelson/tcpflow.git tcpflow_issue_135
    cd tcpflow_issue_135
    ./bootstrap.sh && ./configure && make && make check
    echo $?

I just confirmed that this builds in macOS Sierra.

**Comment by dkogan** [comment]
Alex Nelson <notifications@github.com> writes:

> `make check` in DFXML doesn't seem to do much.  I was satisfied that your change doesn't break the build, but let's check tcpflow too.  Could you try these commands in that same environment?
>
>     git clone --branch=issue_135 https://github.com/ajnelson/tcpflow.git tcpflow_issue_135
>     cd tcpflow_issue_135
>     ./bootstrap.sh && ./configure && make && make check
>     echo $?

This doesn't work because that branch has the broken commit that's
missing the 2 lines. Can you update that branch?

**Comment by ajnelson** [comment]
I apologize for that.  It should go fine now if you delete that clone and re-try.

**Comment by dkogan** [comment]
Alex Nelson <notifications@github.com> writes:

> I apologize for that. It should go fine now if you delete that clone and
> re-try.

OK, that works a lot better. The test suite passes.

**Comment by ajnelson** [comment]
Great to hear.  Thank you for contributing these!  I'll submit the pull request on tcpflow.

**Comment by ajnelson** [comment]
The fix for `hash_t.h` is now in `master`.
