### ISSUE TITLE
Cannot execute fiwalk executable: fiwalk

### ISSUE THREAD

**Issue by dmbina** [simsong/dfxml#17]
I am working on an forensic project for my master thesis. It's about extracting files from a  raw disk image (.E01 or .dd) using python. When I tried to use the fiwalk module, I ran into this error message : 

>>> _import fiwalk_
>>> _f = open("for530ass05.dd")_
>>> _(doc,fobjs) = fiwalk.fileobjects_using_dom(imagefile=f)_

Traceback (most recent call last):
  File "<pyshell#43>", line 1, in <module>
    (doc,fobjs) = fiwalk.fileobjects_using_dom(imagefile=f)
  File "C:\Python27\lib\site-packages\fiwalk.py", line 144, in fileobjects_using_dom
    xmlfile = fiwalk_xml_stream(imagefile=imagefile,flags=flags,fiwalk=fiwalk)
  File "C:\Python27\lib\site-packages\fiwalk.py", line 117, in fiwalk_xml_stream
    raise RuntimeError("Cannot execute fiwalk executable: "+fiwalk)
RuntimeError: Cannot execute fiwalk executable: fiwalk

**Comment by simsong** [comment]
The fiwalk executable is not in your path.

**Comment by dmbina** [comment]
Right. But when i downloaded the repository, there was no fiwalk executable. I don't know where to get it...

**Comment by ajnelson** [comment]
Fiwalk is packaged with The SleuthKit.  If you're on Ubuntu, you can run `sudo apt install sleuthkit` and get it into your path that way.

**Comment by dmbina** [comment]
I'm on Kali, so it should work. thanks. Also i have to specify the path in fiwalk.py, right ?

**Comment by ajnelson** [comment]
You shouldn't have to.

**Comment by dmbina** [comment]
Hey @ajnelson, I want to import the fiwalk module into my script. how did you install it on ubuntu ? I am using python 2.7.12.

**Comment by ajnelson** [comment]
The way I track `fiwalk.py` is by tracking this repository as a Git submodule and then soft-linking the file.

The better way will come when I get back to [Pull request 2](https://github.com/simsong/dfxml/pull/2).  For now, aliasing.

**Comment by simsong** [comment]
Fiwalk.py is a python module that runs fiwalk the executable.
