### ISSUE TITLE
Add __init__.py to DFXML code

### ISSUE THREAD

**Issue by dd388** [simsong/dfxml#18]
As per a comment on a pull request on my own code: "Another, more Pythonic, solution is to fix dfxml to import like a python package by adding __init__.py to dfxml and dfxml/python, and modifying the import statement, but that requires changing multiple packages." See: https://github.com/cul-it/hfs2dfxml/pull/7

**Comment by simsong** [comment]
Done. Can you look at how we include dfxml in fiwalk.py? I'm not entirely happy with it.
