### ISSUE TITLE
needed: dfxml_writer.py

### ISSUE THREAD

**Issue by simsong** [simsong/dfxml#25]
Currently, the only way to create dfxml files from a running program is from C++. We need similar writer for python, so that all of the peculiarities of the runtime environment can be captured.

**Comment by ajnelson-nist** [comment]
I think I see two matters you mean to address with this Issue: A Python script that generates DFXML from a file system walk; and separately, adding more host information to such a script's generated XML, some of which is low-level (e.g. about CPUs).

Addressing the first: There are already two Python programs that generate DFXML from a file system walk. `walk_to_dfxml.py` uses the `Objects.py` read-write bindings for fileobjects, volumes (and soon, disk images and partition systems).  `dfxml_tool.py` uses string templating.

Addressing the second: I hadn't tried supporting things that `dfxml_writer.cpp` generates, like CPU information or Windows rusage information.  I'm not sure how I would get the assembly-provided CPU features (e.g. [here](https://github.com/simsong/dfxml/blob/32ddeab3309ca4e875d743a603a250752d307d7f/src/dfxml_writer.cpp#L388-L406)); we could do something like dump [`platform`](https://docs.python.org/3/library/platform.html)'s output, or maybe munge [this SO snippet](https://stackoverflow.com/a/13078519).

As for vocabulary to use, I poked my head into a few offices down the hall and came up with some similar environment information in ACVP: Here's an [excerpt](https://github.com/usnistgov/ACVP/blob/ed54cc1f9fd13085c411ecb6cabf6660c65357be/artifacts/acvp_protocol.html#L919-L932) from a generated IETF-format document.

    ...
    "operationalEnvironment" : {
        "dependencies" : [{
            "type" : "software",
            "name" : "Linux 3.1",
            "cpe"  : "cpe-2.3:o:ubuntu:linux:3.1"
        },{
            "type" : "processor",
            "manufacturer" : "Intel",
            "family" : "ARK",
            "name" : "Xeon",
            "series" : "5100",
            "features" : [ "rdrand" ]
        }]
    },
    ...

So, I have a few questions for you about this request: What information from `dfxml_writer.cpp` are you looking to port?  [`add_DFXML_execution_environment`](https://github.com/simsong/dfxml/blob/32ddeab3309ca4e875d743a603a250752d307d7f/src/dfxml_writer.cpp#L441), the rest (Windows branch) of [`add_rusage`](https://github.com/simsong/dfxml/blob/32ddeab3309ca4e875d743a603a250752d307d7f/src/dfxml_writer.cpp#L492)...anything else?  And, is the vocabulary in `dfxml_writer.cpp` what you'd like to stick with?

I think this information should only be included in generated DFXML on an opt-in basis.  Also, I'd like it to validate against the DFXML schema, so any first implementations should probably be in a `proposed:` namespace.

**Comment by simsong** [comment]
My goal is that I have a python script for an unrelated project that is going to be run tens of millions of times, and I want a systematic way for collecting memory and CPU usage. I’d also like to capture hostname information, start time, end time, etc. Rather than creating another file format, I thought .. “hey, why don’t I use DFXML?”  And then I discovered that we had no easy module for capturing this.

**Comment by simsong** [comment]
done.
