### ISSUE TITLE
Need License

### ISSUE THREAD

**Issue by simsong** [simsong/dfxml#26]
DFXML needs a license. The majority was done by US Government employees, by a graduate student who is now a USG employee, and there are a few lines that were done by others. 

So I'd like to put a USG no-copyright statement on this. I just need @ajnelson to agree, though, for the works that he did before he became @ajnelson-nist.

@ajnelson, please indicate if you agree here, in this issue, and then close it, and I'll take care of the license issue.

**Comment by ajnelson-nist** [comment]
I've applied a disclaimer to the Python files I've modified under my email addresses.
