### ISSUE TITLE
TSK 4.5.0 - new name_type "V"

### ISSUE THREAD

**Issue by timothyryanwalsh** [simsong/dfxml#27]
Hello,

As described [here](https://github.com/sleuthkit/sleuthkit/issues/998#issuecomment-339742668), TSK 4.5.0 introduces a new name_type of "V" for virtual directories. When Objects.py is used against a fiwalk 4.5.0-generated DFXML file, it raises a ValueError.

**Comment by ajnelson-nist** [comment]
Fixing shortly.  Unfortunately stumbled on an unrelated mild nuisance issue running the unit tests.

**Comment by ajnelson-nist** [comment]
Hi Tim,

Thanks for reporting this.  I've pushed a patch that should fix reading.  I'll leave closing this Issue to you once you've confirmed the fix works for you.

--Alex

**Comment by timothyryanwalsh** [comment]
Hi Alex,

Tested and working beautifully. Thank you!

Tim

**Comment by ajnelson-nist** [comment]
Glad to hear it!
