### ISSUE TITLE
Can't install fiwalk

### ISSUE THREAD

**Issue by RickDeckcard** [simsong/dfxml#36]
My bulk_extractor run ok but I try use identify_filenames.py 
The problem is that I need install fiwalk and dfxml but i can't
I have trying with apt-get, pip3, download in repository (./configure, make, make install), i have trying with setup.py (appear a cmd not found)
I want to install in Kali Linux

When run identify_filenames.py say me that modules fiwalk and dfxml arent in python

**Comment by simsong** [comment]
Hi. Currently bulk_extractor's `identify_filenames.py` requires `fiwalk` to generate the DFXML file that you require. `fiwalk` is part of the SleuthKit release. You will find fiwalk and bulk_extractor pre-installed in [CAINE](https://www.caine-live.net). If you still want to install it yourself, please consult an appropriate tech support forum for SleuthKit.
