### ISSUE TITLE
migrate from travis-CI to GitHub Actions?

### ISSUE THREAD

**Issue by simsong** [simsong/dfxml#37]
This repo is now using Travis-CI, but I'm moving to GitHub actions. Do you want to migrate this to GitHub actions?

**Comment by ajnelson-nist** [comment]
As long as `pytest` and `make check` run on Python's versions [1], I'm personally fine with whichever CI system is used.  I hadn't heard of Github Actions before you mentioned them, so I'm not much help on the actual moving at the moment.

[1] Took me a minute to remember how to find the list of Python's currently supported versions, but here it is:
https://www.python.org/downloads/

**Comment by simsong** [comment]
I'm happy to have it check all supported versions of Python. Can we drop support for Python 2?

**Comment by ajnelson-nist** [comment]
I'm fine dropping Python 2 now that it is past end of life.

**Comment by simsong** [comment]
Personally, I dropped Python 2 in 2007.
