### ISSUE TITLE
Use std::lock_guard

### ISSUE THREAD

**Issue by elfring** [simsong/dfxml#41]
[The file “cppmutex.h” is included](https://github.com/simsong/dfxml/blob/60ebec538f395e56306dc58b0207e361e506b277/src/dfxml_writer.h#L65 "Update candidate"). But it seems that the class “cppmutex” is not used so far.

Would you like to [reuse the standard C++ thread support library](https://en.cppreference.com/w/cpp/thread/lock_guard "Description for std::lock_guard")?

**Comment by simsong** [comment]
Yes. This should be replaced with [std::lock](https://en.cppreference.com/w/cpp/thread/lock) and [std::lock_guard](https://en.cppreference.com/w/cpp/thread/lock_guard).

Thanks for the pointer! They did not exist when this code was written.

**Comment by elfring** [comment]
> They did not exist when this code was written.

Was the support for (standard) C++ threads really so questionable at that point in time?

**Comment by simsong** [comment]
In 2006? Hell no. Threads didn't come till C++11, and weren't widely available for several years.

https://smartbear.com/blog/develop/the-biggest-changes-in-c11-and-why-you-should-care/

**Comment by elfring** [comment]
I noticed that [the statement “`#include "cppmutex.h"`” was added by a commit on 2013-05-10](https://github.com/simsong/dfxml/commit/8915c81dd7a0271cf1e4fcb231acbc8497ea5884 "Added files xml.h and xml.cpp").

-----

When will the proposed class “`std::lock_guard`” [be applied](https://github.com/simsong/dfxml/blob/9f517b7e93031107fe5975107a3fc7b8787fb6b2/src/dfxml_writer.cpp#L607 "Update candidate: dfxml_writer::xmlout()")?

**Comment by simsong** [comment]
Hi. Can you tell me who you are and your interest in this project?

**Comment by elfring** [comment]
I am just someone who would like to achieve a selection of improvements for some software components.
Do you find any (of my) published development activities interesting?

**Comment by simsong** [comment]
> I am just someone who would like to achieve a selection of improvements for some software components.
> Do you find any (of my) published development activities interesting?

I'm thankful for your assistance in pointing out improvements that can be made, but I suspect that I may not have enough bandwidth to make the indicated changes with the speed that you seem to expect. This is a volunteer effort on my part.

**Comment by elfring** [comment]
I propose that you reconsider your imaginations according to my possible expectations.
* I am also unsure in which time frames you would like to see further software evolution happening.
* I hope that you interpret my quick code review in positive ways so far.
