### ISSUE TITLE
Make error response configurable for file output failures

### ISSUE THREAD

**Issue by elfring** [simsong/dfxml#42]
The function “`exit(EXIT_FAILURE)`” is called [after a call of the function “`vasprintf`” failed](https://github.com/simsong/dfxml/blob/9e1a275be166f6ba9f21f22c7ee16c52c143aae2/src/dfxml_writer.cpp#L596 "Update candidate: dfxml_writer::xmlprintf()").
* I would find it occasionally nicer to throw a C++ exception instead.
* How do you think about to use a configurable function for the desired error handling?

**Comment by simsong** [comment]
Thanks for the input, but I think that configurable error responses doesn't make sense, and I can think of no other software package that does this. This is a C++ interface and I think that the correct response is a C++ exception.

**Comment by simsong** [comment]
Somewhat implemented now in https://github.com/simsong/dfxml/blob/slg-dev/src/hash_t.h#L306, but need a test case for it.
