### ISSUE TITLE
Provide a shared library for the Digital Forensics API

### ISSUE THREAD

**Issue by elfring** [simsong/dfxml#43]
Would you like to support the usage of your application programming interface for digital forensics also by known ways as [a shared library](https://en.wikipedia.org/wiki/Library_(computing)#Shared_libraries "Description for the usage of shared libraries")?

**Comment by simsong** [comment]
I don’t think a shared library is useful here, but thank you for the suggestion. This is a pretty small and legacy project.

**Comment by simsong** [comment]
But if you want to make It a shared library, we are happy to take a pill request!
