### ISSUE TITLE
dfxml_writer syntax error on powerpc

### ISSUE THREAD

**Issue by k0da** [simsong/dfxml#5]
endif on line 441 (https://github.com/simsong/dfxml/commit/dd05ebf2db10f5a737bc53b9c0396025a951e022#L0R441) seems should be outside of the function. Otherwise I've got compile error

This fixes issue for me:
--- dfxml_writer.cpporig    2013-09-16 16:34:53.935303000 +0200
+++ dfxml_writer.cpp    2013-09-16 16:35:01.550424000 +0200
@@ -438,8 +438,8 @@
     xmlout("L1_cache_size", (int64_t) BFIX(ecx, 16, 31) \* 1024);
     pop();
 #undef BFIX
-#endif
 }
+#endif

 void dfxml_writer::add_DFXML_execution_environment(const std::string &command_line)
 {

**Comment by simsong** [comment]
I don't think that this is a problem anymore.
