### ISSUE TITLE
doesn't support DFXML files when verifying?

### ISSUE THREAD

**Issue by mgrandi** [simsong/dfxml#56]
Hashdeep and friends seem to only support exporting to XML, but doesn't support reading them back in when verifying with the `-m` option, is this non trivial to add? I remember running into this years ago as well, as there is (still) a lack of tools that can recursively hash files and save them to a exportable format, and DFXML, while overkill, does the job well

**Comment by mgrandi** [comment]
welp, this is embarrassing, this is the wrong repository, sorry

**Comment by simsong** [comment]
No problem. Great to hear from you!
